### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by majklost** [InteractiveComputerGraphics/stark#1]
Hello, I read the paper and I found out that your simulator might be helpful for my research. I would like to know whether the code will be published since there are no updates about the Stark simulator from creating the repository. Thanks for the info ;)

**Comment by JoseAntFer** [comment]
Hello!

Thank you for your interest. The last cleanups to the code and a bit of documentation are being currently made to make sure it's all reasonably understandable. This took a bit more than anticipated. The first release should come in the following days.

Best,
José.

**Comment by majklost** [comment]
Thank you for the information, I am looking forward to the first release ! 

Have a nice day,
Michal
